input_file: ${panza_workspace}/data/${user.username}/test.jsonl
output_path: ""
batch_size: 4
use_thread: false
responses_per_prompt: 1
checkpoint: ${checkpoint}
panza_workspace: ${panza_workspace}
compute_metrics: true
username: ${user.username}
_target_: panza.interface.PanzaJSON