defaults:
  - /writer@assistant: email
  - /writer: email
  # - /writer/llm@assistant.llm: transformers
  # - /writer/llm@personalizer.llm: transformers
  - _self_


_target_: panza.interface.PanzaNiceGUI

assistant: 
  llm:
    #checkpoint:  "Qwen/Qwen3.5-4B"
    checkpoint:  "Qwen/Qwen3-4B-Instruct-2507"

writer: 
  llm:
    #checkpoint:  "Qwen/Qwen3.5-4B"
    checkpoint:  "Qwen/Qwen3-4B-Instruct-2507"

host: localhost
port: 8080
username: ${user.username}
use_pre_personalization_model: true
training_data_path: ${user.data_dir}/train.jsonl
