[project]
name = "panza_mail"
version = "2024.08.14"
description = "A personal email assistant, trained and running on-device."
dependencies = [
    "torch",
    "ollama",
    "omegaconf",
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-dotenv",
    "hydra-core",
    "langchain",
    "langchain-community",
    "sentence-transformers",
    "faiss-cpu",
    "gradio",
    "mauve-text",
    "evaluate",
    "torchmetrics",
    "nltk",
    "accelerate",
    "nicegui",
]

[project.optional-dependencies]
training = [
    "langdetect",
    "fire",
    "gradio",
    "cmake",
    "packaging",
]
contributing = [
    "pre-commit",
]

[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 100

[tool.pytest.ini_options]
pythonpath = ["src"]

[dev-dependencies]
pytest = "*"
