_target_: panza.prompting.SummarizationPromptBuilder

#summarization_prompt: ${load_preamble:${panza_workspace}/prompt_preambles/snippet_summarization_prompt.txt}
summarization_prompt: ${load_preamble:${panza_workspace}/prompt_preambles/snippets_madlib_restatement_prompt.txt}
#summarization_prompt: ${load_preamble:${panza_workspace}/prompt_preambles/snippets3_restatement_prompt.txt}
