defaults:
  - base


max_duration: 3ep
lr: 1e-5
batch_size: 8
train_batch_size: 8
device_train_microbatch_size: 1
eval_interval: 1
seed: ${seed}
#model_name_or_path: "ISTA-DASLab/Meta-Llama-3-8B-Instruct"
#model_name_or_path: "Qwen/Qwen3-4B-Instruct-2507"
model_name_or_path: "Qwen/Qwen3.5-4B"

fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: FULL
  #mixed_precision: BF16
  use_orig_params: false
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  backward_prefetch: BACKWARD_PRE
  forward_prefetch: false
  limit_all_gathers: true
  verbose: false

callbacks:
  hf_checkpointer:
      overwrite: true
      precision: # TODO
      save_folder: ${finetuning.hf_save_path}/${finetuning.run_name}
      save_interval: 1dur

scheduler:
  t_warmup: 20ba
