defaults:
  - base

max_duration: 5ep
lr: 1e-5
batch_size: 8
train_batch_size: 8
device_train_microbatch_size: 1
eval_interval: 8
seed: ${seed}
#model_name_or_path: "Qwen/Qwen3.5-4B"
save_merged_model: False

lora:
  lr: ${finetuning.lr}
  rank: 8
  alpha: 16
  target_modules: 'all-linear'
  dropout: 0.05
  impl: auto
  dtype: bf16
  grad_acc_mode: mean_squared  # 'mean' or 'mean_squared': how to accumulate gradients
  schedule: #TODO

scheduler:
  #constant_with_warmup, cosine_with_warmup, inv_sqrt_with_warmup, linear_decay_with_warmup
  t_warmup: 8ba

num_cpu_threads: 1
