defaults:
  - sampling: random

_target_: panza.llm.TransformersLLM
#name: ${interfaces.checkpoint}
#checkpoint: ${interfaces.checkpoint}
name:  "Qwen/Qwen3.5-4B"
checkpoint:  "Qwen/Qwen3.5-4B"
device: ${oc.env:PANZA_DEVICE,cuda}  # supports: cuda, cpu, mps, mlx
dtype: "bf16"
load_in_4bit: false
remove_prompt_from_stream: true
