email_address: "david_anonymous@xyz.com"  # Change this to your email address!
username: "snippets"  # This identifies the user in the users directory and the names of the emails files.

data_dir: ${panza_workspace}/data/snippets

system_preamble_path: ${panza_workspace}/prompt_preambles/snippet_system_preamble.txt
user_preamble_path: ${panza_workspace}/prompt_preambles/david_preamble.txt
rag_preamble_path: ${panza_workspace}/prompt_preambles/rag_preamble.txt
thread_preamble_path: ${panza_workspace}/prompt_preambles/thread_preamble.txt
